eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/     #http://eureka1:8761/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
server:
  port: 8762

spring:
  application:
    name: eureka2

#management:
#  server:
#    servlet:
#      context-path: /
